version: "3"

services:

  client1:
    container_name: load0
    image: equic:local
    command: /src/equic/docker/load-test-entrypoint.sh
    environment:
      - REQ_SIZE=$REQ_SIZE
    volumes:
      - ..:/src/equic

  client2:
    container_name: load1
    image: equic:local
    command: /src/equic/docker/load-test-entrypoint.sh
    environment:
      - REQ_SIZE=$REQ_SIZE
    volumes:
      - ..:/src/equic

  client3:
    container_name: load2
    image: equic:local
    command: /src/equic/docker/load-test-entrypoint.sh
    environment:
      - REQ_SIZE=$REQ_SIZE
    volumes:
      - ..:/src/equic

  client4:
    container_name: load3
    image: equic:local
    command: /src/equic/docker/load-test-entrypoint.sh
    environment:
      - REQ_SIZE=$REQ_SIZE
    volumes:
      - ..:/src/equic

networks:
  default:
    external:
      name: docker_equic
