version: "3"

services:

  server:
    container_name: equic-server
    image: equic:local
    volumes:
      - ..:/src/equic
      - ../CMakeLists.txt:/src/lsquic/bin/CMakeLists.txt
      - ../echo_server.c:/src/lsquic/bin/echo_server.c
      - ../http_server.c:/src/lsquic/bin/http_server.c
    cap_add: # Necessary to modify network interface
      - NET_ADMIN
      - SYS_ADMIN
    networks:
      - equic
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1

  client0:
    container_name: client0
    image: equic:local
    command: tail -f
    volumes:
      - ..:/src/equic
    networks:
      - equic

networks:
  equic:
