version: "3"

services:

  server:
    container_name: equic-server
    image: equic:local
    command: tail -f
    volumes:
      - ..:/src/equic
    cap_add: # Necessary to modify network interface
      - NET_ADMIN
      - SYS_ADMIN
    networks:
      - equic
    restart: always

  client:
    container_name: equic-client
    image: equic:local
    command: tail -f
    volumes:
      - ..:/src/equic
    networks:
      - equic

networks:
  equic:
