version: "3"

services:

  client5:
    container_name: parallel0
    image: equic:local
    command: /src/equic/docker/load-test-entrypoint.sh
    environment:
      - REQ_SIZE=$REQ_SIZE
      - PARALLEL=1
    volumes:
      - ..:/src/equic

  client6:
    container_name: parallel1
    image: equic:local
    command: /src/equic/docker/load-test-entrypoint.sh
    environment:
      - REQ_SIZE=$REQ_SIZE
      - PARALLEL=1
    volumes:
      - ..:/src/equic

  client7:
    container_name: parallel2
    image: equic:local
    command: /src/equic/docker/load-test-entrypoint.sh
    environment:
      - REQ_SIZE=$REQ_SIZE
      - PARALLEL=1
    volumes:
      - ..:/src/equic

  client8:
    container_name: parallel3
    image: equic:local
    command: /src/equic/docker/load-test-entrypoint.sh
    environment:
      - REQ_SIZE=$REQ_SIZE
      - PARALLEL=1
    volumes:
      - ..:/src/equic

networks:
  default:
    external:
      name: docker_equic
